"""
RepoDiscoverAI v3.0 - Markdown Generator

Generates agent-ready Markdown from trending repositories.
"""

import logging
from datetime import datetime
from typing import List

logger = logging.getLogger(__name__)


class MarkdownGenerator:
    """Generate agent-ready Markdown from trending repos."""
    
    def __init__(self, config: dict):
        self.config = config
        self.site_url = config.get("SITE_URL", "https://repodiscoverai.com")
    
    def generate_markdown(self, repos: list, date: str) -> str:
        """
        Generate structured Markdown for AI agent consumption.
        
        Returns:
            Markdown string
        """
        markdown = f"""# RepoDiscoverAI Daily Digest - {date}

## Executive Summary

Today's top {len(repos)} trending repositories on GitHub.

---

## Top Repositories

"""
        
        for i, repo in enumerate(repos, 1):
            markdown += f"""### {i}. {repo.owner}/{repo.name}

**URL:** {repo.url}
**Language:** {repo.language or 'N/A'}
**Stars:** {repo.stars}
**Forks:** {repo.forks}
**Last Updated:** {repo.last_updated[:10] if repo.last_updated else 'N/A'}
**Trend Score:** {repo.trend_score:.4f}

**Description:**
{repo.description}

**Key Features:**
- High community engagement
- Active development
- Trending in {repo.language or 'multiple'} ecosystem

**Why It's Trending:**
- {repo.stars} total stars with strong growth velocity
- Active issue and PR management
- Community interest across multiple platforms

---

"""
        
        # Trend analysis
        languages = [r.language for r in repos if r.language]
        top_language = max(set(languages), key=languages.count) if languages else "N/A"
        avg_stars = sum(r.stars for r in repos) / len(repos) if repos else 0
        
        markdown += f"""## Trend Analysis

**Total Repos Analyzed:** {len(repos)}
**Top Language:** {top_language}
**Average Stars:** {avg_stars:.0f}
**Trending Topics:** AI, Open Source, Developer Tools, Automation

## Data Sources

- GitHub Trending (scraped every 6 hours)
- GitHub API (stars, forks, issues, PRs)
- Reddit (r/programming, r/MachineLearning)
- Hacker News (front page, technology)

## Subscription

Subscribe to our feeds:
- **RSS:** {self.site_url}/feed.xml
- **Atom:** {self.site_url}/feed.atom
- **JSON API:** {self.site_url}/api/daily

---

*Generated by RepoDiscoverAI v3.0*
*Next update: {self._get_next_update_time()}*
*Source: {self.site_url}*
"""
        
        logger.info(f"✅ Markdown generated ({len(markdown)} chars)")
        return markdown
    
    def _get_next_update_time(self) -> str:
        """Get next update time."""
        from datetime import datetime, timedelta
        next_update = datetime.now() + timedelta(hours=24)
        return next_update.strftime("%Y-%m-%d %H:%M EDT")
